### ISSUE TITLE
Fehlermeldung beim Mailversand

### ISSUE THREAD

**Issue by Schmidty2** [hschottm/contao_memberlist#8]
Ich habe in einer Testinstallation das folgende Problem mit memberlist 1.3.1 Bulid 8:

Wenn ich als angemeldetes Mitglied eine Nachricht (E-Mail) an ein anderes Mitglied schicke, wird die E-Mail zwar verschickt, aber der folgende Eintrag in die error.log geschrieben:

PHP Recoverable error: Argument 1 passed to Contao\ModuleMemberlist::sendPersonalMessage() must be an instance of Contao\Database_Result, instance of Contao\MemberlistMemberModel given, called in /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/memberlist/modules/ModuleMemberlist.php on line 326 and defined in /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/memberlist/modules/ModuleMemberlist.php on line 365
#0 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/memberlist/modules/ModuleMemberlist.php(365): __error(4096, 'Argument 1 pass...', '/is/htdocs/wp10...', 365, Array)
#1 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/memberlist/modules/ModuleMemberlist.php(326): Contao\ModuleMemberlist->sendPersonalMessage(Object(Contao\MemberlistMemberModel), Object(Contao\FormTextArea))
#2 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/memberlist/modules/ModuleMemberlist.php(76): Contao\ModuleMemberlist->listSingleMember('3')
#3 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/modules/Module.php(282): Contao\ModuleMemberlist->compile()
#4 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/memberlist/modules/ModuleMemberlist.php(61): Contao\Module->generate()
#5 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/elements/ContentModule.php(59): Contao\ModuleMemberlist->generate()
#6 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#7 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#8 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#9 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#10 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#11 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#12 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#13 /is/htdocs/XXXXXXXX/www/verzeichnisname/system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#14 /is/htdocs/XXXXXXXX/www/verzeichnisname/index.php(20): Contao\FrontendIndex->run()
#15 {main}

Das Testszenario liegt bei HostEurope auf einem Virtual Server Managed 5.0 XL. Es ist ein neu installiertes Contao 3.2.21, mit easyupdate auf 3.5.3 aktualisiert. Außer easyupdate3 3.3.0 Build 0 und tivoka 1.0.2 Build 7 ist nur noch memberlist 1.3.1 Build 8 installiert.
Der Contao-Check meldet keine Fehler. Auf dem Hostingpaket laufen weitere Contao-Installationen problemlos. Der Mailversand erfolgt über Mail, ein SMTP-Server ist nicht eingetragen. Zum Test wurde ein Kontaktformular erstellt, das problemlos funktioniert.
Auch wenn ein SMTP-Server eingetragen ist, besteht das Problem. Die E-Mail-Adressen wurden auf Richtigkeit überprüft.

Ein Backend-Adminzugang und ein FTP-Zugang zur Testinstallation kann gerne zur Verfügung gestellt werden.

**Comment by Schmidty2** [comment]
Hallo,

ich habe Memberlist in unter Contao 3.5.6 Version 1.3.1 Build 8 auf Build 9 aktualisiert (vom ER).
Nach dem Update werden wieder Fehler protokolliert. BugBuster hat im Beitrag https://community.contao.org/de/showthread.php?50894-Probleme-mit-Erweiterung-quot-Memberlist-quot weiter (#9) am 15.06.2015 um 01:59 bereits die Lösung gepostet:

Probiere mal und gehe in die Datei /system/modules/memberlist/modules/ModuleMemberlist.php in Zeile 365 und mache aus

protected function sendPersonalMessage(Database_Result $objMember, Widget $objWidget)
protected function sendPersonalMessage($objMember, Widget $objWidget)

Kann das bitte in der nächsten Aktualisierung mit aufgenommen werden?
==> Ich hatte das im Build 8 händisch geändert, nach dem Update auf Build 9 war der Fehler wieder vorhanden.

Danke.

**Comment by hschottm** [comment]
Fixed in 5cc1384c4c3ef9e68341137ab642ff2d909ccef4

**Comment by brederode** [comment]
Hallo Herr Schottmüller, 

ich habe Memberlist (Contao) in eine Internetplattform verwendet. 
Beim E-Mail-Versand von Bewerber an Unternehmen und von Unternehmen an Bewerber kommt eine E-Mail: "Das Profil des Absenders finden Sie hier: 'https://www.############. 
Es gibt leider eine Zugriffsverweigerung auf der Internetplattform, weil die Bewerber- und Unternehmensseiten auf bestimmten erlaubte Mitgliedergruppen geschützt sind. 
Wie kann ich dieses Problem lösen?

Danke.
