### ISSUE TITLE
Contao 3.5.12 Template nicht mehr auswählbar

### ISSUE THREAD

**Issue by jammon88** [hschottm/contao_memberlist#9]
Guten Tag

Bei einer frischen Contao 3.5.12 Installation fehlen beim Modul Memberlist diverse Felder bei der Modulkonfiguration. Beispielsweise ist es nicht möglich, eine Weiterleitungsseite zu definitieren oder ein anderes Template auszuwählen. Können Sie dies prüfen?
Hier ein Printscreen von Contao 3.5.12:
![contao3 5 12](https://cloud.githubusercontent.com/assets/2118269/15069561/b1c87a50-137e-11e6-8b2e-e77eddf8a06a.png)

Und hier der Printscreen von Contao 3.5.9:
![contao3 5 9](https://cloud.githubusercontent.com/assets/2118269/15069560/b1c73fe6-137e-11e6-8b4d-80b94ee921d8.png)

Besten Dank

Jammon

**Comment by hschottm** [comment]
Das ist kein Fehler im memberlist-Modul. Alle diese zusätzlichen Felder werden von der Erweiterung xtmembers hinzugefügt. Die müssten Sie dann auch noch installieren und dann bekommen Sie auch wie gewohnt die Felder für die Listenvorlage und die Sortieroptionen.
